const nouns = ['action items',
    'alignments',
    'applications',
    'architectures',
    'bandwidth',
    'benefits',
    'best practices',
    'catalysts for change',
    'channels',
    'clouds',
    'collaboration and idea-sharing',
    'communities',
    'content',
    'convergence',
    'core competencies',
    'customer service',
    'data',
    'deliverables',
    'e-business',
    'e-commerce',
    'e-markets',
    'e-tailers',
    'e-services',
    'experiences',
    'expertise',
    'functionalities',
    'fungibility',
    'growth strategies',
    'human capital',
    'ideas',
    'imperatives',
    'infomediaries',
    'information',
    'infrastructures',
    'initiatives',
    'innovation',
    'intellectual capital',
    'interfaces',
    'leadership',
    'leadership skills',
    'manufactured products',
    'markets',
    'materials',
    'meta-services',
    'methodologies',
    'methods of empowerment',
    'metrics',
    'mindshare',
    'models',
    'networks',
    'niches',
    'niche markets',
    'nosql',
    'opportunities',
    '"outside the box" thinking',
    'outsourcing',
    'paradigms',
    'partnerships',
    'platforms',
    'portals',
    'potentialities',
    'rocess improvements',
    'processes',
    'products',
    'quality vectors',
    'relationships',
    'resources',
    'results',
    'ROI',
    'scenarios',
    'schemas',
    'scrums',
    'services',
    'solutions',
    'sources',
    'sprints',
    'strategic theme areas',
    'storage',
    'supply chains',
    'synergy',
    'systems',
    'technologies',
    'technology',
    'testing procedures',
    'total linkage',
    'users',
    'value',
    'vortals',
    'web-readiness',
    'web services',
    'wins',
    'virtualization'];
const adverbs = ['appropriately',
    'assertively',
    'authoritatively',
    'collaboratively',
    'compellingly',
    'competently',
    'completely',
    'continually',
    'conveniently',
    'credibly',
    'distinctively',
    'dramatically',
    'dynamically',
    'efficiently',
    'energistically',
    'enthusiastically',
    'fungibly',
    'globally',
    'holisticly',
    'interactively',
    'intrinsically',
    'monotonectally',
    'objectively',
    'phosfluorescently',
    'proactively',
    'professionally',
    'progressively',
    'quickly',
    'rapidiously',
    'seamlessly',
    'synergistically',
    'uniquely'];
const adjectives = [
    '24/365',
    'accurate',
    'adaptive',
    'agile',
    'alternative',
    'B2B',
    'B2C',
    'backend',
    'backward-compatible',
    'best-of-breed',
    'bleeding-edge',
    'bricks-and-clicks',
    'business',
    'clicks-and-mortar',
    'client-based',
    'client-centered',
    'client-centric',
    'client-focused',
    'cloud-based',
    'cloud-centric',
    'cloudified',
    'collaborative',
    'compelling',
    'competitive',
    'cooperative',
    'corporate',
    'cost effective',
    'covalent',
    'cross functional',
    'cross-media',
    'cross-platform',
    'cross-unit',
    'customer directed',
    'customized',
    'cutting-edge',
    'distinctive',
    'distributed',
    'diverse',
    'dynamic',
    'e-business',
    'economically sound',
    'effective',
    'efficient',
    'elastic',
    'emerging',
    'empowered',
    'enabled',
    'end-to-end',
    'enterprise',
    'enterprise-wide',
    'equity invested',
    'error-free'];
const verbs = ['actualize',
    'administrate',
    'aggregate',
    'architect',
    'benchmark',
    'brand',
    'build',
    'cloudify',
    'communicate',
    'conceptualize',
    'coordinate',
    'create',
    'cultivate',
    'customize',
    'deliver',
    'deploy',
    'develop',
    'dinintermediate disseminate',
    'drive',
    'embrace',
    'e-enable',
    'empower',
    'enable',
    'engage',
    'engineer',
    'enhance',
    'envisioneer',
    'evisculate',
    'evolve',
    'expedite',
    'exploit',
    'extend',
    'fabricate',
    'facilitate',
    'fashion',
    'formulate',
    'foster',
    'generate',
    'grow',
    'harness',
    'impact',
    'implement',
    'incentivize',
    'incubate',
    'initiate',
    'innovate',
    'integrate',
    'iterate',
    'leverage existing',
    'leverage other\'s',
    'maintain',
    'matrix',
    'maximize',
    'mesh',
    'monetize',
    'morph',
    'myocardinate',
    'negotiate',
    'network',
    'optimize',
    'orchestrate',
    'parallel task',
    'plagiarize',
    'pontificate',
    'predominate',
    'procrastinate',
    'productivate',
    'productize',
    'promote',
    'provide access to',
    'pursue',
    'recaptiualize',
    'reconceptualize',
    'redefine',
    're-engineer',
    'reintermediate',
    'reinvent',
    'repurpose',
    'restore',
    'revolutionize',
    'right-shore',
    'scale',
    'seize',
    'simplify',
    'strategize',
    'streamline',
    'supply',
    'syndicate',
    'synergize',
    'synthesize',
    'target',
    'transform',
    'transition',
    'underwhelm',
    'unleash',
    'utilize',
    'visualize',
    'whiteboard'
];

const makePhrase = () => {
    const nounIndex = Math.floor((Math.random() * nouns.length) + 1);
    const adverbsIndex = Math.floor((Math.random() * adverbs.length) + 1);
    const adjectivesIndex = Math.floor((Math.random() * adjectives.length) + 1);
    const verbsIndex = Math.floor((Math.random() * verbs.length) + 1);

    console.log(nounIndex, adverbsIndex, adjectivesIndex, verbsIndex);
};

makePhrase();
